name: Get var

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Get secret
        env:
          coin_token: ${{ secrets.COIN_TOKEN }}
        run: echo $coin_token
